version: '3.1'
services:
   mysqldb:
    image: mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=rootpassword 
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost -p rootpassword || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
      
   product:
    image: springjpa
    ports:
      - "9992:8080"
    environment:
      - DB_URL=jdbc:mysql://mysqldb:3306/mysql
      - DB_USERNAME=root
      - DB_PASSWORD=rootpassword
    depends_on:
      - mysqldb
    restart: always